# Default values for product-service.

image:

autoscaling:
  enabled: true
  minReplicas: 2 # Start with 2 replicas for HA
  maxReplicas: 7
  targetCPUUtilizationPercentage: 60
  repository: your-ecr-repo/product-service  # ECR 리포지토리 주소로 변경 필요
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
