apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-auth-service.fullname" . }}
  labels:
    {{- include "user-auth-service.labels" . | nindent 4 }}
    component: authentication
    domain: user
data:
  config.yaml: |
    jwt:
      accessTokenExpiration: {{ .Values.config.jwt.accessTokenExpiration }}
      refreshTokenExpiration: {{ .Values.config.jwt.refreshTokenExpiration }}
      issuer: {{ .Values.config.jwt.issuer }}
      algorithm: {{ .Values.config.jwt.algorithm }}
    
    oauth:
      google:
        enabled: {{ .Values.config.oauth.google.enabled }}
        clientId: {{ .Values.config.oauth.google.clientId }}
      github:
        enabled: {{ .Values.config.oauth.github.enabled }}
        clientId: {{ .Values.config.oauth.github.clientId }}
    
    security:
      bcryptRounds: {{ .Values.config.security.bcryptRounds }}
      maxLoginAttempts: {{ .Values.config.security.maxLoginAttempts }}
      lockoutDuration: {{ .Values.config.security.lockoutDuration }}
      sessionTimeout: {{ .Values.config.security.sessionTimeout }}
    
    rateLimiting:
      enabled: {{ .Values.config.rateLimiting.enabled }}
      loginAttempts: {{ .Values.config.rateLimiting.loginAttempts }}
      windowMs: {{ .Values.config.rateLimiting.windowMs }}