apiVersion: v2
name: user-notification-service
description: A Helm chart for the user-notification-service microservice (Multi-channel Notification System)

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: base-chart
  version: "0.1.0"
  repository: "file://../base-chart"