apiVersion: v2
name: user-auth-service
description: A Helm chart for the user-auth-service microservice (Authentication & JWT Management)

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: base-chart
  version: "0.1.0"
  repository: "file://../base-chart"