apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-api-service.fullname" . }}
  labels:
    {{- include "order-api-service.labels" . | nindent 4 }}
    component: order-api
    domain: order
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "order-api-service.selectorLabels" . | nindent 4 }}