apiVersion: v2
name: order-api-service
description: A Helm chart for the order-api-service microservice (Order Processing API)

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: base-chart
  version: "0.1.0"
  repository: "file://../base-chart"