apiVersion: v2
name: product-search-service
description: A Helm chart for the product-search-service microservice (Search Engine)

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: base-chart
  version: "0.1.0"
  repository: "file://../base-chart"