apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-inventory-service.fullname" . }}
  labels:
    {{- include "product-inventory-service.labels" . | nindent 4 }}
    component: inventory-management
    domain: product
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "product-inventory-service.selectorLabels" . | nindent 4 }}