apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: app-of-apps
    app.kubernetes.io/part-of: microservices-platform
spec:
  project: default
  source:
    repoURL: https://github.com/jasonethicseo/elice-pjt.git # 모노레포의 주소로 변경
    targetRevision: HEAD
    path: helm-charts # 루트 애플리케이션 경로
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: order-domain
spec:
  project: default
  source:
    repoURL: oci://YOUR_AWS_ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/aws-ecr-elice-pjt-helm-charts-order
    targetRevision: 0.1.0 # Assuming initial chart version
    chart: order-service
    helm:
      valueFiles:
        - https://github.com/jasonethicseo/elice-pjt.git/helm-charts/order-service/values.yaml # Path to values.yaml in Git
  destination:
    server: https://kubernetes.default.svc
    namespace: order
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: product-domain
spec:
  project: default
  source:
    repoURL: oci://YOUR_AWS_ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/aws-ecr-elice-pjt-helm-charts-product
    targetRevision: 0.1.0 # Assuming initial chart version
    chart: product-service
    helm:
      valueFiles:
        - https://github.com/jasonethicseo/elice-pjt.git/helm-charts/product-service/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: product
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: user-domain
spec:
  project: default
  source:
    repoURL: oci://YOUR_AWS_ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com/aws-ecr-elice-pjt-helm-charts-user
    targetRevision: 0.1.0 # Assuming initial chart version
    chart: user-service
    helm:
      valueFiles:
        - https://github.com/jasonethicseo/elice-pjt.git/helm-charts/user-service/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: user
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m