name: Publish Helm Charts to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'helm-charts/**'

env:
  AWS_REGION: ca-central-1
  ECR_HELM_REPO_PREFIX: aws-ecr-${{ github.event.repository.name }}-helm-charts

jobs:
  publish-helm-charts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the OIDC ID token
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout private modules
        uses: actions/checkout@v4
        with:
          repository: jasonethicseo/elice-pjt-modules
          token: ${{ secrets.PRIVATE_MODULES_TOKEN }}
          path: temp-modules
          
      - name: Setup modules directory
        run: |
          cp -r temp-modules/modules ./
          rm -rf temp-modules

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCExecutionRole # Replace with your actual IAM Role ARN
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Login to Amazon ECR for Helm
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | helm registry login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Package and Push base-chart
        run: |
          helm package ./helm-charts/base-chart
          helm push base-chart-0.1.0.tgz oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_HELM_REPO_PREFIX }}-base

      - name: Package and Push order-service chart
        run: |
          helm dependency update ./helm-charts/order-service
          helm package ./helm-charts/order-service
          helm push order-service-0.1.0.tgz oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_HELM_REPO_PREFIX }}-order

      - name: Package and Push product-service chart
        run: |
          helm dependency update ./helm-charts/product-service
          helm package ./helm-charts/product-service
          helm push product-service-0.1.0.tgz oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_HELM_REPO_PREFIX }}-product

      - name: Package and Push user-service chart
        run: |
          helm dependency update ./helm-charts/user-service
          helm package ./helm-charts/user-service
          helm push user-service-0.1.0.tgz oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_HELM_REPO_PREFIX }}-user
